services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "plantarium_app"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - plantarium_network

  db:
    image: postgres:latest
    container_name: "plantarium_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - plantarium_network

volumes:
  pgdata:

networks:
  plantarium_network:
    driver: bridge
