services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "plantarium-api"
    restart: always
    ports:
      - "${WEB_PORT}:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?schema=public
    depends_on:
      db:
        condition: service_healthy
    networks:
      - plantarium_network
    volumes:
      - ./:/app

  db:
    image: postgres:16-alpine
    container_name: "plantarium-db"
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - plantarium_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  plantarium_network:
    driver: bridge
